# Generated by Django 4.1.3 on 2022-11-29 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('place', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('permis', models.CharField(max_length=50)),
                ('carte_identité', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('localité', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('numero_chaise', models.IntegerField()),
                ('heure_depart', models.DateTimeField(auto_now_add=True)),
                ('heure_arrive', models.DateTimeField(auto_now_add=True)),
                ('numero_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminpanel.car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('trajet', models.CharField(max_length=50)),
                ('heure_depart', models.DateTimeField(auto_now_add=True)),
                ('heure_arrive', models.DateTimeField(auto_now_add=True)),
                ('numero_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminpanel.car')),
                ('numero_chaise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminpanel.ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='conducteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminpanel.chauffeur'),
        ),
    ]
