# Generated by Django 4.1.3 on 2022-11-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('gerant', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=50)),
                ('heure_ouverture', models.DateTimeField(auto_now_add=True)),
                ('heure_fermeture', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='assistant',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom_gare',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('carte', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('poste', models.CharField(max_length=50)),
                ('idgare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminpanel.gare')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminpanel.gare'),
        ),
    ]
