# Generated by Django 4.1.3 on 2022-12-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adminpanel', '0003_remove_reservation_user_remove_ticket_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prenom', models.CharField(max_length=128)),
                ('ville', models.CharField(max_length=128)),
                ('residence', models.CharField(max_length=128)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sexe', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
